use_frameworks!

platform :ios, '11.0'

target 'mylib_Example' do
  pod 'mylib', :path => '../'

  target 'mylib_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 2.2.0'
    pod 'Nimble', '~> 10.0.0'
  end
end
